services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=taskdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - af-network
    command: mongod --bind_ip_all

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/taskdb
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=taskdb
    depends_on:
      - mongodb
    networks:
      - af-network

networks:
  af-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local